RANDPAR(1)
==========


NAME
----
randpar - prints a random parameter on stdout


SYNOPSIS
--------
*randpar* [*-0*|*--print0*] [*-n* 'K'] [*-a*|*--all*] 'arguments'...


DESCRIPTION
-----------
*randpar* prints one (or some) of the parameters passed by command line.


OPTIONS
-------
*-n* 'K'::
	Set the number of parameters to print, default is one parameter.

*-0*, *--print0*::
	Output null character instead of linebreaks to separate parameters.  This
	is provided to be used in conjunction with xargs -0.  This overrides any
	calls to *-d*.

*-d*, *--delimiter*='D'::
	Output the character 'D' as delimiter instead of linebreaks.  This
	overrides *-0*.

*-a*, *--all*::
	Outputs all parameters passed in a random order.

*-h*, *--help*::
	Shows help.

*-v*, *--version*::
	Shows version.

*-r*, *--repeat*::
	Allow parameters to be repeated.

*-s*, *--seed*::
	Fixes the random seed (deterministic behaviour).


BUGS
----
Report bugs to rudy@matela.com.br


SEE ALSO
--------
*fit*(1), *hilite*(1), *hl*(1), *untl*(1), *sgetopt*(3)


COPYRIGHT
---------
Copyright (C) 2013 Rudy Matela. Free use of this software is granted under the
terms of the GNU General Public License version 2 or any later version.

