'\" t
.\"     Title: ched
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 2013-09-16
.\"    Manual: \ \&
.\"    Source: evenmoreutils
.\"  Language: English
.\"
.TH "CHED" "1" "2013\-09\-16" "evenmoreutils" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ched \- cached command run
.SH "SYNOPSIS"
.sp
\fBched\fR \fIcommand\fR
.SH "DESCRIPTION"
.sp
\fBched\fR is a cached command runner\&. At the first time running a command, (ca)\fBched\fR stores its output in a cache\&. At subsequent calls to the command with \fBched\fR, up to a certain time threshold, the output of cache is used\&.
.sp
This is a prototype version\&.
.sp
Caution should be noted when using this to run commands with side effects\&.
.SH "OPTIONS"
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Shows help (not implemented)
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Shows version (not implemented)
.RE
.PP
\fB\-t\fR, \fB\-\-timeout\fR=\fISECONDS\fR
.RS 4
Holds cache until
\fISECONDS\fR
seconds\&. Default is 10 seconds\&. (not implemented)
.RE
.PP
\fB\-e\fR, \fB\-\-cache\-stderr\fR
.RS 4
Activates stderr caching\&. (not implemented)
.RE
.PP
\fB\-\-dont\-cache\-on\-error\fR
.RS 4
Don\(cqt cache on error\&. (not implemented)
.RE
.PP
\fB\-\-ignore\-working\-dir\fR
.RS 4
Ignore working dir when chaching\&. This should be used with commands that do not have a different output when executed on different working directories\&.
.RE
.PP
\fB\-s\fR, \fB\-\-shell\-exec\fR
.RS 4
For default, ched executes commands directly\&. Use this option to execute commands with \(lqsh \-c\(rq\&. This is useful when running bash functions for example\&.
.RE
.PP
\fB\-x\fR, \fB\-\-exec\fR
.RS 4
Reverts the effect of
\fI\-s\fR
option\&.
.RE
.SH "EXAMPLES"
.sp
\fBched ls\fR
.sp
Does a cached list of a directory\&.
.sp
\fBched hg status\fR
.sp
Does a mercurial status command on some directory\&. This might be useful when implementing scripts for bash smart completion\&.
.sp
\fBched links \-dump example\&.com/friends_list\fR
.sp
Does a cached access of a url\&.
.SH "BUGS"
.sp
Report bugs to rudy@matela\&.com\&.br
.SH "SEE ALSO"
.sp
\fBage\fR(1)
.SH "COPYRIGHT"
.sp
Copyright \(co 2013 Rudy Matela\&. Free use of this software is granted under the terms of the GNU General Public License version 2 or any later version\&.
