#!/bin/bash
#
# This could be implemented in C for maximum efficiency (the actual purpose of the cache)
#
# For now, a quick-and-dirty version in shell:

cache_timeout=5
if [ "$1" == "-t" ]
then
	cache_timeout="$2"
	shift 2
fi

md5() {
	echo "`pwd` $@" |
	md5sum |
	head -c 32
}

the_cache="$HOME/.cache/ched/`md5 "$@"`"

if age --newer $cache_timeout $the_cache
then
	cat $the_cache
else
	$@ | tee $the_cache
fi
