#!/bin/bash
#
# fit - truncates a stream by fitting it into a certain width
#
# Copyright (C) 2012, 2013  Rudy Matela
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
#
# Fit, fits text withing $1 columns (or $COLUMNS) or crop it! :D
#
# TODO: Maybe reimplement in C when doing evenmoreutils

columns=$1
[ -z "$columns" ] && columns=$COLUMNS
[ -z "$columns" ] && columns=`tput cols`
[ -z "$columns" ] && columns=`stty size | sed -e 's/.* //'`
[ -z "$columns" ] && columns=80

sed -ue "s/\t/        /" | sed -ue "s/\\(.\{$columns\}\\).*/\1/"
