.TH MIME 1
.SH NAME
mime \- determine file mimetype
.SH SYNOPSIS
.B mime
\fIfile\fR ...
.SH DESCRIPTION
.B mime
determines the file mimetype. It is just an alias for file -bi
.SH BUGS
The manpage is longer than the code.

Report bugs to rudy@matela.com.br
.SH SEE ALSO
\fBfit\fR(1), \fBmime\fR(1), \fBnup\fR(1), \fBp\fR(1), \fBpad\fR(1), \fBrandpar\fR(1), \fBuntl\fR(1), \fBsgetopt\fR(3)
.SH COPYRIGHT
.sp
Copyright (C) 2013 Rudy Matela. Free use of this software is granted under the
terms of the GNU General Public License version 2 or any later version.
