#!/bin/bash
#
# nup - n-up an output from a program (making it two, or n columns)
#
# Copyright (C) 2012, 2013  Rudy Matela
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
#
# nup command
#
# Examples:
#
# $ cat somefile.txt
# This is a
# test file
# with 4 lines
# to test nup
#
# $ cat somefile.txt | nup
# This is a     with 4 lines
# test file     to test nup
#
# $ nup somefile.txt
# This is a     with 4 lines
# test file     to test nup
#
# $ nup -4 somefile.txt
# This is a     test file    with 4 lines     to test nup
#
# $ nup -s somefile.txt  # puts a separator
# This is a  |  with 4 lines
# test file  |  to test nup
#
# $ nup -i somefile.txt  # inversion mode
# This is a     test file
# with 4 lines  to test nup
#
# TODO: Ended up a bit different from planned, redocument

while [ "$#" -gt 0 ]; do
	case $1 in
	-*n) splitpars="$splitpars -n $2"; shift ;;
	-*l) splitpars="$splitpars -l $2"; shift ;;
     -d) pastepars="$pastepars -d $2"; shift ;;
	 -*)                                         ;;
	  *) files="$files $1"                       ;;
	esac
	shift
done

tmpdir=`mktemp -d -t nup.XXXXXXXXXX` &&
cat $files > $tmpdir/original &&
split $splitpars $tmpdir/original $tmpdir/nup- &&
paste $pastepars $tmpdir/nup-*
rm -r $tmpdir
