.TH P 1
.SH NAME
p \- runs processes in parallel and wait for their termination
.SH SYNOPSIS
.B p
[\fB\-h\fR]
[\fB\-v\fR]
[\fB\-c\fR\fI COLOR\fR]
[\fB\-b\fR]
[\fB\-u\fR]
[\fB\-r\fR]
[\fB\-n\fR]
.IR command
[
[\fIOPTIONS\fR]
.IR command ...
]
.SH DESCRIPTION
.B p
runs processes in parallel and wait for their termination.  The processes can be
marked to have different colors and the output can be tagged with the processes
names (in fact, this is the original main purpose of the script).

An idea for the future, is to have a parameter ``-&'' to indicate that commands
will be separated by \\&.  And wihout it they must be passed by using quotes
"process1 arg1" "process2 arg2" (This is the current setting).
.SH OPTIONS
.TP
.BR \-h
Shows help (not implemented)
.TP
.BR \-v
Shows version (not implemented)
.TP
.BR \-c " " \fICOLOR\fR
Sets the color, can be: black, red, green, yellow, blue, magenta, cyan or
white.
.TP
.BR \-b
Bold output (active if no color or style is passed).
.TP
.BR \-u
Underlined output
.TP
.BR \-r
Reverse output
.TP
.BR \-n
Normal output (reset)
.TP
.BR \-t
Sets a tag / title to be printed along with the process.
.SH EXAMPLES
.nf
.B p -bc blue """ping 127.0.0.1""" -uc red """ping 192.168.0.1""" -rc yellow """ping 192.168.1.1""" -t example """ping example.com"""
.fi

Runs 4 ping processes in parallel. The first pinging localhost with output in
bold and blue color.  The second, 192.168.0.1, underlined with red color. The
third reversed with yellow color.  The fourth tagged with title example.

.nf
.B p """tail -f /var/log/httpd/access_log""" -bc red """tail -f /var/log/httpd/error_log"""
.fi

Runs two ``tail -f''s in one terminal.  One with apache access log, the other
with the apache error log highlighted in red.

.nf
.B p tail -f /var/log/httpd/access_log \\\\& -bc red tail -f /var/log/httpd/error_log
.fi

or

.nf
.B p tail -f /var/log/httpd/access_log """&""" -bc red tail -f /var/log/httpd/error_log
.fi

Same command as above written in a different way.  \fBThis is not currently
supported.\fR  It is interesting because you can pass a parameter as ``"blah
bleh"'' which is impossible in the first version in which the space will always
be used to separate the parameters. If your shell does not treat & as a special
char you can just put it plain on the command line. Example of usefulness:

.nf
.B p tail -f """some file""" \\\\& p tail -f """some other file with space in the name.txt"""
.fi

.SH BUGS
Report bugs to rudy@matela.com.br

Does not work with title (``-t'') having a slash (``/'').  That'll be corrected on
future versions.
.SH SEE ALSO
\fBfit\fR(1), \fBhilite\fR(1), \fBhl\fR(1), \fBmime\fR(1), \fBnup\fR(1), \fBpad\fR(1), \fBrandpar\fR(1), \fBuntl\fR(1), \fBsgetopt\fR(3)
.SH COPYRIGHT
.sp
Copyright (C) 2013 Rudy Matela. Free use of this software is granted under the
terms of the GNU General Public License version 2 or any later version.
