#!/bin/bash
#
# pad - pads output with whitespaces to fit a certain width
#
# Copyright (C) 2012, 2013  Rudy Matela
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
#
# pad command
#
# pads stdin with whitespaces and writes to stdout
#
# for now it's fitting tightly using fit
#
# width is passed as $1
#
# does not work with width > 80
#
# TODO: Maybe reimplement in C when doing evenmoreutils

sed -e "s/$/`printf " "%.0s {1..80}`/" | fit $1


