.TH RANDPAR 1
.SH NAME
randpar \- prints a random parameter on stdout
.SH SYNOPSIS
.B randpar
[\fB\-0\fR|\fB\-\-print0\fR]
[\fB\-n\fR\fI K\fR]
[\fB\-a\fR|\fB\-\-all\fR]
.IR file ...
.SH DESCRIPTION
.B randpar
prints one (or some) of the parameters passed by command line
.SH OPTIONS
.TP
.BR \-n " " \fIK\fR
Set the number of parameters to print, default is one parameter
.TP
.BR \-0 ", " \-\-print0
Output null character instead of linebreaks to separate parameters.
This is provided to be used in conjunction with xargs -0
.TP
.BR \-a ", " \-\-all
Outputs all parameters passed in a random order.
.SH BUGS
Report bugs to rudy@matela.com.br

If you pass a string as a parameter to \fB-n\fR the program will consider
\fIK\fR as 0 and will fail with \fISIGSEGV\fR. That'll be corrected on future
versions.
.SH SEE ALSO
\fBfit\fR(1), \fBhilite\fR(1), \fBhl\fR(1), \fBmime\fR(1), \fBnup\fR(1), \fBp\fR(1), \fBpad\fR(1), \fBuntl\fR(1), \fBsgetopt\fR(3)
.SH COPYRIGHT
.sp
Copyright (C) 2013 Rudy Matela. Free use of this software is granted under the
terms of the GNU General Public License version 2 or any later version.
