.TH UNTL 1
.SH NAME
untl, whle, repeat \- run a command repeatedly, until/while it is sucessful
.SH SYNOPSIS
.B untl
[\fB\-i\fR INTERVAL\fR]
[\fB\-l\fR LIMIT\fR]
[\fB\-r\fR RETVAL\fR]
[other options]
\fIcommand\fR
.br
.B whle
[\fB\-i\fR INTERVAL\fR]
[\fB\-l\fR LIMIT\fR]
[\fB\-r\fR RETVAL\fR]
[other options]
\fIcommand\fR
.br
.B repeat
[\fB\-i\fR INTERVAL\fR]
[\fB\-l\fR LIMIT\fR]
[\fB\-r\fR RETVAL\fR]
[other options]
\fIcommand\fR
.SH DESCRIPTION
.B untl
calls a process until it is successful.
.br
.B whle
calls a process while it is successful, in other words, until it fails.
.br
.B repeat
calls a process repeatedly.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Shows help
.TP
.BR \-v ", " \-\-version
Shows version
.TP
.BR \-u ", " \-\-untl
Forces untl behavior (default when program name is different from whle or repeat)
.TP
.BR \-w ", " \-\-whle
Forces whle behavior (default when program name is whle)
.TP
.BR \-\-repeat
Forces repeat behavior (default when program name is repeat)
.TP
.BR \-r ", " \-\-retval " " \fIRETVAL\fR
Runs a processes until (or while) the return value equals \fIRETVAL\fR when in
\fBuntl\fR or \fBwhle\fR mode.  When in \fBrepeat\fR mode, this option has no
effect.
.TP
.BR \-i ", " \-\-interval " " \fIINTERVAL\fR
Sets the interval, in seconds, of each try.  Default is 1.  This option does
accept floating point values.
.TP
.BR \-l ", " \-\-limit " " \fILIMIT\fR
Limit the number of tries.
.SH EXAMPLES
.nf
.B untl ping example.com
.fi

Tries to ping example.com until it is successful.

.nf
.B untl ls /var/spool/printer
.fi

Tries to list contents of /var/spool/printer until it is successful.

.SH BUGS
Report bugs to rudy@matela.com.br
.SH SEE ALSO
\fBfit\fR(1), \fBhilite\fR(1), \fBhl\fR(1), \fBmime\fR(1), \fBnup\fR(1), \fBp\fR(1), \fBpad\fR(1), \fBrandpar\fR(1), \fBsgetopt\fR(3)
.SH COPYRIGHT
.sp
Copyright (C) 2013 Rudy Matela. Free use of this software is granted under the
terms of the GNU General Public License version 2 or any later version.
