#!/bin/bash
#
# anywait - like wait, but works on any pid of the system
#
# Copyright (C) 2012, 2013  Rudy Matela
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
# TODO: Check if this works with zombie processes
# TODO: Make this work on zombie process
# TODO: Make this work when you dont want to care about zombie processes
# TODO: Implement -i switch to tell the interval to query for the processes
# TODO: Implement timeout switch

anywait() {
    for pid in "$@"; do
        while [ -d /proc/$pid ]; do
            sleep 0.5
        done
    done
}

anywait "$@"

