#!/bin/bash
#
# Sponges to a file only if the contents would be changed
#
# Copyright (C) 2012, 2013  Rudy Matela
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

spongif-quit() {
	rm $tmpfile
	exit 0
}

dstfile="$1"
tmpfile=`mktemp -t spongif.XXXXXXXXXX` &&
cat > $tmpfile &&
diff -q $dstfile $tmpfile > /dev/null && spongif-quit
cat $tmpfile > $dstfile &&
rm -f $tmpfile
